# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('proposition_1', models.TextField()),
                ('proposition_2', models.TextField()),
                ('proposition_3', models.TextField(null=True)),
                ('proposition_4', models.TextField(null=True)),
            ],
        ),
    ]
