# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceBDD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='nbPersonneValideTest',
            field=models.IntegerField(default=0),
        ),
    ]
